name: cht_bot
description: "A new Flutter project."
publish_to: 'none' # Jangan publish ke pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Package Gemini (AI)
  google_generative_ai: ^0.4.0

  # Baca API Key dari file .env
  flutter_dotenv: ^6.0.0

  # Untuk upload gambar
  image_picker: ^1.2.0

  # Untuk upload file PDF, Excel, dll
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter untuk memastikan kode rapi
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
